tabs:
  general:
    display: 'General'
    sections:
      -
        fields:
          -
            handle: email_field
            field:
              display: 'Email Field'
              instructions: 'The form field that contains the email of the subscriber.'
              type: statamic_form_fields
              validate: 'required'
              width: 50
          -
            handle: list_id
            field:
              display: 'Audience'
              instructions: 'The Mailchimp audience you want to add the subscriber to.'
              type: mailchimp_pro_audience
              mode: select
              max_items: 1
              validate: 'required'
              width: 50
          -
            handle: consent_field
            field:
              display: 'Consent Field'
              instructions: 'The form field that contains the consent of the subscriber.'
              type: statamic_form_fields
              width: 50
          -
            handle: tag_id
            field:
              display: 'Tag'
              instructions: 'The Mailchimp tag you want to add to the subscriber.'
              type: mailchimp_pro_tag
              width: 50
          -
            handle: merge_fields
            field:
              display: 'Merge Fields'
              instructions: 'Add the form fields you want to map to Mailchimp fields.'
              type: grid
              mode: table
              listable: hidden
              fullscreen: false
              width: 100
              add_row: 'Add Merge Field'
              fields:
                -
                  handle: statamic_field
                  field:
                    display: 'Form Field'
                    type: statamic_form_fields
                -
                  handle: mailchimp_field
                  field:
                    display: 'Merge Field'
                    type: mailchimp_pro_merge_fields
